import AuthContext from '@/components/AuthContext'
import './globals.css'
import type { Metadata } from 'next'
import { Providers } from '../redux/provider'
import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry'
import { BaseContainer } from '@/styles/Layout'

export const metadata: Metadata = {
  title: "WithPT",
  description: "Generated by withPT",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Providers>
            {/* <AuthContext> */}
              <StyledComponentsRegistry>
                <BaseContainer>{children}</BaseContainer>
              </StyledComponentsRegistry>
            {/* </AuthContext> */}
        </Providers>
      </body>
    </html>
  );
}
